name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in pietrzakadrian.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://pietrzakadrian.com/blog/rss"

  update-readme-with-podcast:
    name: Update this repo's README with latest podcasts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in pietrzakadrian.com posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://pietrzakadrian.com/podcast/rss"
          comment_tag_name: "PODCAST-LIST"
